#set page(
  paper: "us-letter",
  margin: 1in,
)
#set text(
  font: "New Computer Modern",
  size: 11pt,
)
#set par(justify: true, leading: 0.55em)
#show heading.where(level: 1): set text(size: 13pt)
#show heading.where(level: 2): set text(size: 11pt)
#show heading: set block(above: 1.1em, below: 0.7em)
#show link: set text(fill: rgb("#0645ad"))

#grid(
  columns: (1fr, auto),
  align: (left + bottom, right + bottom),
  [
    #text(size: 15pt, weight: "bold")[Geoffrey Challen] \
    Teaching Professor, Siebel School of Computing and Data Science \
    The Grainger College of Engineering, University of Illinois Urbana-Champaign
  ],
  text(size: 9pt)[#link("mailto:challen@illinois.edu")[challen\@illinois.edu]],
)

#v(-0.2em)
#line(length: 100%, stroke: 0.5pt)

== Biosketch

Geoffrey Challen earned an AB in Physics from Harvard in 2003 and a PhD in Computer Science from Harvard in 2010, where his dissertation on data fidelity and resource management for data-rich sensor networks was advised by Matt Welsh. He completed a postdoctoral fellowship at MIT in 2010–2011 with Hari Balakrishnan. From 2011 to 2017 he was an Assistant Professor at the University at Buffalo, where he led the blue Systems Research Group in mobile systems and received an NSF CAREER Award (2017) for research on implementation flexibility and runtime adaptation in mobile systems. He joined the University of Illinois as Associate Teaching Professor in 2017 and was promoted to Teaching Professor in 2024. In 2026 he received the Grainger College of Engineering's Rose Award for Teaching Excellence and the Siebel School's Scott H. Fisher Computer Science Teaching Award—the school's top honor for undergraduate teaching. He has chaired the Instructional Computing Committee since 2023, served on the University General Education Board (2022–2024), and was the first teaching-faculty chair of the teaching faculty hiring committee.

== Known For

Challen is known for reinventing CS1 at scale. Since taking over Illinois's introductory programming course (now CS 124) in Fall 2017, enrollment has doubled to over 2,000 students per year, drop rates have fallen, success rates and downstream performance have risen, and a gender performance gap has disappeared. Over 21 terms at Illinois he has taught 16,107 students. He builds the software his courses run on: Jeed, a JVM execution and analysis toolkit that runs untrusted code 1000× faster than alternatives; Questioner, which accelerates programming-exercise authoring 10×; interactive walkthroughs; autogenerated debugging and testing exercises; and code-quality autograding. He publishes his CS1 materials openly at #link("https://learncs.online")[learncs.online] and introduced Kotlin alongside Java as a CS1 language. He has previously received nearly \$3M in external research funding from the NSF and Google.

== Current Areas of Emphasis

Challen's current work responds to the way AI has changed what it means to build—and therefore to teach—computing. He has redesigned CS 124 around AI coding agents: every student now designs and builds their own Android application with an agent, while classical programming is assessed through proctored quizzes. He piloted CS 199 UAI: Using and Understanding AI in Spring 2026 for non-technical students and is launching its permanent form, CS 108: Exploring Generative AI, in Spring 2027. He is also designing CS 199 ASK: Conversational Programming, a Fall 2026 course with no prerequisites where students learn to work like architects—exploring problems, prototyping with AI, and iterating through conversation. He is leading the design of Applied Computing, a proposed four-year undergraduate degree at Illinois organized around studio-based design, domain integration, and AI-assisted building. Supporting infrastructure includes a novel two-agent conversational assessment system and interactive AI demos, with entire course platforms built through conversation with AI coding agents.

== Website

#link("https://geoffreychallen.com")[geoffreychallen.com]
